### ISSUE TITLE
"Startup breakpoints" are not caught when using launch.json config type "chrome".

### ISSUE THREAD

**Issue by floooh** [microsoft/vscode-dwarf-debugging-ext#2]
First: this extension is extremely awesome!

I've been tinkering around a bit and use it with the following launch.json file to debug Emscripten WASM targets running in Chrome (together with the CMake Tools extension):

```json
{
 "version":"0.2.0",
 "configurations":[
  {
   "type":"chrome",
   "request":"launch",
   "name":"Debug in Chrome",
   "url":"http://localhost:8080/${command:cmake.launchTargetFilename}",
   "server":{
    "program":"httpserver.js",
   }
  }
 ]
}
```

The httpserver.js helper script starts a node http-server like so:

```js
const { execSync } = require('child_process');
execSync('http-server -c-1 -g .', {
  cwd: '[path with index.html]',
  stdio: 'inherit',
  stderr: 'inherit',
});
```

...now when pressing F5, this will start a http-server, Chrome, and a debug session in VSCode, which all in all works wonderfully.

Only problem I have is that "early breakpoints" in the C code are not caught, for instance a breakpoint at the start of main() is not detected, only breakpoints that also trigger later (for instance in the per-frame callback).

It **does** work in the following situations:

- when using the palette command 'Debug: Open Link' instead of launch.json
- or when restarting a debugging session via 'Restart' button in the VSCode debugging controls

I've been looking for something like a "wait for debugger to attach" option in the launch.json attributes, but without luck.

TBH I don't know if this can even be fixed in the DWARF extension, or whether this is a problem of the `chrome` launch configuration, but it's soooo close to perfect that it would be wonderful if it can be fixed somehow :)

Cheers!

**Comment by floooh** [comment]
Here in this movie you can see that it takes a few frames until a breakpoint in the frame callback is caught, and later I set a breakpoint in the init function which is immediately caught when restarting the debug session:

https://github.com/microsoft/vscode-dwarf-debugging-ext/assets/1699414/bf17bdf7-46bc-458a-b037-148519f17062

**Comment by connor4312** [comment]
Fixed in on the nightly extension https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension

**Comment by floooh** [comment]
Awesome! Thanks!

**Comment by floooh** [comment]
Btw, do I read this right that WASM DWARF debugging will eventually move into core VSCode (e.g. no additional extensions required?)

**Comment by connor4312** [comment]
No, it'll always be separate. VS Code is a ~150MB download and the DWARF debugging stuff is in a big 30MB (compressed) WASM binary. We wouldn't take a 20% overall size increase for such a niche feature

**Comment by floooh** [comment]
Argh, hmm ok, it works "sometimes" but I also quite often get an error looking like this instead (in a new vscode tab with a title like `VM46947589`:

`Could not load source 'chromewebdata/(index)꞉6839:9': Source not found.`

When refreshing the page the debug session starts and breakpoints are hit (e.g. the same workaround as before).

Is this a bug in the `vscode-dwarf-debugging` extension or should I report that `vscode-js-debug` repo?
