### ISSUE TITLE
My breakpoints are not being hit

### ISSUE THREAD

**Issue by mmarczell-graphisoft** [microsoft/vscode-dwarf-debugging-ext#4]
My breakpoints are not getting hit and my C++ sources are not appearing under "Loaded scripts". However I have seen this working just a few minutes ago and it just broke unexplainably. What can I do to investigate what's happening?

(For example my WASM file, which includes the DWARF debuginfo, is over 400MB, because of a medium large codebase. Might this be the problem for the extension? Can the extension be instructed to print logs about errors encountered?)

**Comment by NickelWenzel** [comment]
I just had the same problem and managed to solve/work around the issue.

My setup is that i compile some C++ codebase using CMake the emscripten toolchain which generates two files a **my_code.wasm** with the corresponding **my_code.js**. For me breaking in the c++ code worked when first setting a breakpoint in the **callMain** function of the *.js file. I hope this helps.

It would greatly improve the extension if this wouldn't be necessary or at least be documented.

**Comment by mmarczell-graphisoft** [comment]
> my C++ sources are not appearing under "Loaded scripts".

I looked a bit further and it seems that the issue might be related to multithreading / Web Workers. The extension seems to only load my sources in some but not all of my 20 workers. Therefore the breakpoint being hit depends on which thread hits it.

**Comment by connor4312** [comment]
You might be running into a race setting breakpoints which should be fixed in [nightly](https://github.com/microsoft/vscode-js-debug/?tab=readme-ov-file#nightly-extension) by https://github.com/microsoft/vscode-js-debug/pull/2102

**Comment by connor4312** [comment]
Closing this because it's fairly old, but if that doesn't solve your issue let me know!
