### ISSUE TITLE
Does this plugin work for browser WASM debugging?

### ISSUE THREAD

**Issue by ecorm** [microsoft/vscode-dwarf-debugging-ext#9]
I'm trying to debug a large WASM file via the browser using this plugin and I cannot get it to load any C++ source or hit any C++ breakpoints. It just now occurs to me that this plugin may only be for server-side node debugging.

Please clarify, and update the plugin descriptions accordingly.

**Comment by ecorm** [comment]
Nevermind, just found this blurb under https://code.visualstudio.com/docs/nodejs/browser-debugging:

| WebAssembly debugging in browsers is identical to Node.js, [read more about WebAssembly Debugging here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_debugging-webassembly).

**Comment by floooh** [comment]
FWIW I wrote a blog post about this a little while ago:

https://floooh.github.io/2023/11/11/emscripten-ide.html
